apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  sources:
    - chart: kube-state-metrics
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "*"
      helm:
        releaseName: kube-state-metrics
  project: project-default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
