config:
  clients:
    - url: http://vmsingle-victoria-logs.victoria.svc.cluster.local:8429/insert/loki/api/v1/push
      external_labels:
        collector: promtail
relabel_configs:
  - source_labels: ['__meta_kubernetes_pod_node_name']
    target_label: '__host__'
