# see https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
config:
  clients:
    - url: http://vlsingle-victoria-logs.victoria-logs.svc.cluster.local:9428/insert/loki/api/v1/push
      external_labels:
        collector: promtail
