config:
  clients:
    - url: http://vlsingle-victoria-logs.victoria-logs.svc.cluster.local:9428/insert/loki/api/v1/push
      external_labels:
        collector: promtail
relabel_configs:
  - source_labels: ['__meta_kubernetes_pod_node_name']
    target_label: '__host__'
  - source_labels: ['msg']
    target_label: '_msg'
