image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.9.10
enableRbac: true
serviceAccount:
  name: homepage
  create: true
envFrom:
  - configMapRef:
      name: homepage-configmap
config:
  kubernetes:
    mode: cluster
  bookmarks:
    - developer:
        - Github:
            - abbr: GH
              href: https://github.com/adaptivekind/app-of-apps
    - lab:
        - ArgoCD:
            - abbr: AR
              href: https://argocd.{{HOMEPAGE_VAR_LAB_DOMAIN}}/
        - Grafana:
            - abbr: GR
              href: https://grafana.{{HOMEPAGE_VAR_LAB_DOMAIN}}/
        - Prometheus:
            - abbr: PR
              href: https://prometheus.purplepip.com/
        - PiHole:
            - abbr: PH
              href: https://pihole.{{HOMEPAGE_VAR_LAB_DOMAIN}}/
  services: {}
  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
