image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.9.10
enableRbac: true
serviceAccount:
  name: homepage
  create: true

config:
  kubernetes:
    mode: cluster
  bookmarks: {}
  services: {}
  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
