# See https://loki.{{lab_domain}}/config for applied config
# See https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
# for how they are set in the chart (there are subtle differences)
global:
  extraArgs:
    - -log.level warn
deploymentMode: SingleBinary
loki:
  image:
    tag: 3.5.1
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem
        schema: v13
  frontend:
    address: 127.0.0.1
  #   max_outstanding_per_tenant: 1
  #   parallelise_shardable_queries: false
  # query_scheduler:
  #   max_outstanding_requests_per_tenant: 1
  # limits_config:
  #   split_queries_by_interval: 0
  # Test https://github.com/grafana/loki/pull/17562 when version
  # after 3.5.1 released
  # ui:
  #   enabled: true
gateway:
  verboseLogging: false
sidecar:
  rules:
    logLevel: ERROR
singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
chunksCache:
  allocatedMemory: 1024
test:
  enabled: false
lokiCanary:
  enabled: false
