# See https://loki.{{lab_domain}}/config for applied config
deploymentMode: SingleBinary
loki:
  auth_enabled: false
  common:
    replication_factor: 1
  storage:
    type: "filesystem"
  schema_config:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem
        schema: v13
  frontend:
    address: 127.0.0.1
singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
chunksCache:
  allocatedMemory: 1024
