apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nut
    name: in-cluster
  project: default
  source:
    path: apps/nut
    repoURL: https://github.com/adaptivekind/app-of-apps
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
