apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-otel-instrumentation
  namespace: examples
spec:
  selector:
    matchLabels:
      app: example-otel-instrumentation
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "monitoring/opentelemetry-collector"
      labels:
        app: example-otel-instrumentation
    spec:
      containers:
        - image: ghcr.io/adaptivekind/example-otel-instrumentation-express:latest
          name: example-otel-instrumentation
          env:
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: NODE_OPTIONS
              value: "--require @opentelemetry/auto-instrumentations-node/register"
            - name: OTEL_NODE_RESOURCE_DETECTORS
              value: env,host,os,serviceinstance
