apiVersion: v1
kind: Service
metadata:
  name: otel-instrumentation
  namespace: examples
spec:
  ports:
    - name: api
      port: 3000
      targetPort: 3000
    - name: collector-metrics
      port: 8888
      targetPort: 8888
    - name: http-metrics
      port: 8889
      targetPort: 8889
  selector:
    app: example-otel-instrumentation
  type: ClusterIP
