apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-instrumentation
  namespace: examples
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: otel-instrumentation
  endpoints:
  - port: http-metrics
