apiVersion: v1
kind: Service
metadata:
  name: otel-instrumentation
  namespace: examples
spec:
  ports:
    - name: api
      port: 3000
      targetPort: 3000
    - name: metrics
      port: 8888
      targetPort: 8888
  selector:
    app: example-otel-instrumentation
  type: ClusterIP
