apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demo-install
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - chart: opentelemetry-demo
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: "*"
      helm:
        releaseName: opentelemetry-demo
  project: default
  destination:
    name: in-cluster
    namespace: opentelemetry-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
