apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: lens
    name: in-cluster
  project: project-default
  source:
    path: apps/promtail/default
    repoURL: https://github.com/adaptivekind/app-of-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
