# https://github.com/DRuggeri/nut_exporter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nut-deployment
  namespace: power
  labels:
    app: nut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nut
  template:
    metadata:
      labels:
        app: nut
      annotations:
        sidecar.opentelemetry.io/inject: otel/otel-sidecar
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: nut
        image: druggeri/nut_exporter:3.2
        args:
          - --web.listen-address=:8082
          - --web.telemetry-path=/metrics
          - --web.exporter-telemetry-path=/self-metrics
        ports:
        - containerPort: 8082
        env:
          - name: NUT_EXPORTER_SERVER
            value: 0.0.0.0
          - name: NUT_EXPORTER_VARIABLES
            value: >
              battery.charge,
              ups.load,
              ups.realpower,
              ups.status
