apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry
spec:
  mode: daemonset
  config:
    receivers:
      kubeletstats:
        collection_interval: 10s
        auth_type: serviceAccount
        endpoint: '${env:K8S_NODE_NAME}:10250'
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/*/otel-collector/*.log
        start_at: end
        include_file_path: true
        include_file_name: false
        operators:
          - type: container
            id: container-parser

    exporters:
      debug:
        verbosity: detailed
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        logs_endpoint: http://vlsingle-victoria-logs.victoria-logs.svc.cluster.local:9428/insert/opentelemetry/v1/logs
        tls:
          insecure: true
      prometheus:
        endpoint: prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090

    service:
      pipelines:
        metrics:
          exporters:
            - prometheus
          receivers:
            - kubeletstats
        logs:
          exporters:
            - otlphttp/victoriametrics
          receivers:
            - filelog
