apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry
spec:
  mode: sidecar
  config:
    processors:
      resourcedetection:
        detectors: [env, system]
      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 800
      batch:
        send_batch_size: 10000
        timeout: 10s

    receivers:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu: {}
          disk: {}
          filesystem: {}
          load: {}
          memory: {}
          network: {}
          paging: {}
      otlp:
        protocols:
          grpc:
            endpoint: 127.0.0.1:4317
          http:
            endpoint: 127.0.0.1:4318

    exporters:
      otlp:
        endpoint: "tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
      debug: {}

    service:
      pipelines:
        metrics:
          receivers:
            - otlp
            - hostmetrics
          exporters:
            - debug
            - prometheus
        logs:
          receivers:
            - otlp
          exporters:
            - debug
        traces:
          exporters:
            - otlp
            - debug
          receivers:
            - otlp
