apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - chart: opentelemetry-operator
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/apps/opentelemetry/values.yaml
    - repoURL: https://github.com/adaptivekind/app-of-apps
      targetRevision: HEAD
      ref: values
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
