apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-sidecar
spec:
  mode: sidecar
  env:
    - name: NAMESPACE_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_UID
      valueFrom:
        fieldRef:
          fieldPath: metadata.uid
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-sidecar
              scrape_interval: 5s
              static_configs:
                - targets: ["0.0.0.0:8082"]
    exporters:
      debug:
        verbosity: detailed
      otlp/grpc:
        endpoint: otel-gateway-collector.otel.svc.cluster.local:4317
        tls:
          insecure: true
    processors:
      attributes:
        actions:
          - action: insert
            key: metric.source
            value: otel-sidecar
          - action: insert
            key: k8s.pod.uid
            value: ${POD_UID}
          - action: insert
            key: k8s.pod.ip
            value: ${POD_IP}
          - action: insert
            key: k8s.pod.name
            value: ${POD_NAME}
          - action: insert
            key: k8s.namespace.name
            value: ${NAMESPACE_NAME}
    service:
      pipelines:
        metrics:
          receivers:
            - prometheus
          processors:
            - attributes
          exporters:
            - otlp/grpc
