apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: prometheus-sidecar
spec:
  mode: sidecar
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 5s
              static_configs:
                - targets: ['0.0.0.0:8888']

    processors: {}

    exporters:
      debug: {}
      otlp/grpc:
        endpoint: 'otel-collector.opentelemetry.svc.cluster.local:4317'
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [prometheus]
          exporters: [debug, otlp/grpc]
