apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: prometheus-sidecar
spec:
  mode: sidecar
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 5s
              static_configs:
                - targets: ['0.0.0.0:8082']

    processors: {}

    exporters:
      debug:
        verbosity: detailed
      otlp/grpc:
        endpoint: otel-collector.opentelemetry.svc.cluster.local:4317

    service:
      pipelines:
        metrics:
          receivers: 
            - prometheus
          exporters:
            - otlp/grpc
