apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  mode: sidecar
  config:
    memory_limiter:
      check_interval: 1s
      limit_mib: 4000
      spike_limit_mib: 800
    processors:
      resourcedetection:
        detectors: [env, system]
    batch:
      send_batch_size: 10000
      timeout: 10s

    receivers:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu:
          disk:
          filesystem:
          load:
          memory:
          network:
          paging:
      otlp:
        protocols:
          grpc:
            endpoint: 127.0.0.1:4317
          http:
            endpoint: 127.0.0.1:4318

    exporters:
      otlp:
        endpoint: "tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      debug: {}

    service:
      pipelines:
        metrics:
          exporters:
            - debug
          receivers:
            - otlp
            - hostmetrics
        logs:
          exporters:
            - debug
          receivers:
            - otlp
        traces:
          exporters:
            - otlp
            - debug
          receivers:
            - otlp
