apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  mode: daemonset
  presets:
    kubernetesAttributes:
      enabled: true
    kubeletMetrics:
      enabled: true
    logsCollection:
      enabled: true
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 127.0.0.1:4317
          http:
            endpoint: 127.0.0.1:4318

    exporters:
      debug: {}

    service:
      pipelines:
        metrics:
          exporters:
            - debug
          receivers:
            - otlp
        logs:
          exporters:
            - debug
          receivers:
            - otlp
        traces:
          exporters:
            - debug
          receivers:
            - otlp
