apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-gateway
  namespace: otel
spec:
  mode: daemonset
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:HOST_IP}:4317
          http:
            endpoint: ${env:HOST_IP}:4318
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu: {}
          load: {}
          memory:
            metrics:
              # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/documentation.md
              system.linux.memory.available:
                enabled: true
              system.memory.limit:
                enabled: true
              system.memory.utilization:
                enabled: true
          network: {}
          paging: {}
          processes: {}

      hostmetrics/slow:
        collection_interval: 5m
        scrapers:
          disk: {}
          filesystem: {}
          system: {}
      
      kubeletstats:
        collection_interval: 30s
        auth_type: serviceAccount
        endpoint: '${env:K8S_NODE_NAME}:10250'
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container
          - volume

      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/*/otel-collector/*.log
        start_at: end
        include_file_path: true
        include_file_name: false
        operators:
          - type: container
            id: container-parser

    processors:
      batch: {}
      batch/metrics:
        send_batch_max_size: 200
        send_batch_size: 200
        timeout: 180s
      k8sattributes:
        # https://opentelemetry.io/docs/platforms/kubernetes/collector/components/#kubernetes-attributes-processor
        auth_type: serviceAccount
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
          labels:
            - tag_name: app.label.component
              key: app.kubernetes.io/component
              from: pod
          otel_annotations: true
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

    exporters:
      debug: {}
        # verbosity: detailed
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        logs_endpoint: http://vlsingle-victoria-logs.victoria-logs.svc.cluster.local:9428/insert/opentelemetry/v1/logs
        tls:
          insecure: true
      prometheusremotewrite:
        external_labels:
          collector: otel
        remote_write_queue:
          enabled: true
          num_consumers: 1
          queue_size: 500
        resource_to_telemetry_conversion:
          enabled: true
        send_metadata: true
        endpoint: http://prometheus-operated.prometheus.svc.cluster.local:9090/api/v1/write
        tls:
          insecure: true
      prometheusremotewrite/grafana:
        external_labels:
          collector: otel
        remote_write_queue:
          enabled: true
          num_consumers: 1
          queue_size: 500
        resource_to_telemetry_conversion:
          enabled: true
        send_metadata: true
        endpoint: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
        auth:
          authenticator: basicauth

    extensions:
      basicauth:
        client_auth:
          username: "${REMOTE_PROMETHEUS_WRITE_USERNAME}"
          password: "${REMOTE_PROMETHEUS_WRITE_PASSWORD}"

    service:
      extensions:
        - basicauth
      pipelines:
        metrics:
          exporters:
            - prometheusremotewrite
            - prometheusremotewrite/grafana
          processors:
            - batch/metrics
            - k8sattributes
          receivers:
            - otlp
            - kubeletstats
            - hostmetrics
            - hostmetrics/slow
        # logs:
        #   exporters:
        #     - otlphttp/victoriametrics
        #   receivers:
        #     - filelog
      telemetry:
        logs:
          level: INFO
          development: false
          encoding: json

  env:
  - name: REMOTE_PROMETHEUS_WRITE_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
        name: remote-prometheus-write-credentials
  - name: REMOTE_PROMETHEUS_WRITE_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: remote-prometheus-write-credentials

