apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-extras
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: default
  source:
    path: apps/traefik
    repoURL: https://github.com/adaptivekind/app-of-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
