apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: k3d-grafana-route
  namespace: monitoring
spec:
  routes:
    - match: Host(`grafana.local`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls:
    secretName: grafana-server-tls
