apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespacce: kube-system
  name: redirect-to-dashbaord
spec:
  redirectRegex:
    regex: ^http://([^\/]*)/$
    replacement: http://${1}/dashboard/
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: traefik-route
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNIRegexp(`traefik.{domain:[a-z\.]+}`)
      middleware:
        - redirect-to-dashbaord
      services:
        - name: traefik-dashboard
          namespace: kube-system
          port: 9000
  tls:
    secretName: traefik-server-tls
