apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: traefik-route
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNIRegexp(`traefik.{domain:[a-z\.]+}`)
      services:
        - name: traefik-dashboard
          namespace: kube-system
          port: 9000
  tls:
    secretName: traefik-server-tls
