apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-route
  namespace: traefik-extras
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`traefik.{domain:[a-z\.]+}`)
      middlewares:
        - name: redirect-to-dashbaord
          namespace: kube-system
      services:
        - kind: TraefikService
          name: api@internal
          namespace: kube-system
  tls:
    secretName: traefik-server-tls
