apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - chart: alloy
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: "*"
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
