apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb-route
  namespace: influxdb
spec:
  routes:
    - match: Headers("Service", "influxdb")
      kind: Rule
      services:
        - name: influxdb
          port: 8086
