apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-logs-grafana-datasource
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: victoria-logs
    type: victoriametrics-logs-datasource
    url: http://vmsingle-victoria-logs.victoria.svc.cluster.local:8429
    access: proxy
    isDefault: true
  plugins:
    - name: victoriametrics-logs-datasource
      version: 0.17.0

