apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs-install
  namespace: argocd
spec:
  sources:
    - chart: victoria-metrics-operator
      repoURL: ghcr.io/victoriametrics/helm-charts
      targetRevision: "*"
      helm:
        releaseName: victoria-logs
  project: default
  destination:
    name: in-cluster
    namespace: victoria
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

