apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: victoria-logs-route
  namespace: victoria-logs
spec:
  routes:
    - match: HostRegexp(`victoria-logs.{domain:[a-z\.]+}`)
      kind: Rule
      services:
        - name: vlsingle-victoria-logs
          port: 9428
