apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-install
  namespace: argocd
spec:
  sources:
    - chart: keda
      repoURL: https://kedacore.github.io/charts
      targetRevision: "2.17"
      helm:
        releaseName: keda
  project: default
  destination:
    name: in-cluster
    namespace: keda
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      # to fix metadata.annotations: Too long: must have at most 262144 bytes
      - ServerSideApply=true
