apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-grafana-datasource
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: prometheus
    type: prometheus
    url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
    access: proxy
    isDefault: true
    jsonData:
      "tlsSkipVerify": true
      "timeInterval": "5s"
