apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - chart: grafana-operator
      repoURL: ghcr.io/grafana/helm-charts
      targetRevision: v5.18.0
  project: default
  destination:
    name: in-cluster
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
