apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  sources:
    - chart: grafana-operator
      repoURL: ghcr.io/grafana/helm-charts/grafana-operator
      targetRevision: "v5.12.0"
  project: project-default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
