apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  routes:
    - match: HostRegexp(`grafana.{domain:[a-z\.]+}`)
      kind: Rule
      services:
        - name: grafana-service
          port: 3000
