apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - chart: grafana-operator
      repoURL: ghcr.io/grafana/helm-charts
      targetRevision: "v5.12.0"
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
