apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  external:
    url: https://grafana.purplepip.com
    adminPassword:
      name: grafana-password
      key: admin-password
    adminUser:
      name: grafana-password
      key: admin-user
