apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
spec:
  secretName: grafana-server-tls
  secretTemplate:
    label:
      cluster-issuer: ca-issue
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - Adaptive Kind
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.local
