apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-install
  namespace: argocd
spec:
  sources:
    - chart: tempo
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: "*"
      helm:
        releaseName: tempo
        valueFiles:
          - $values/apps/tempo/values.yaml
    - repoURL: https://github.com/adaptivekind/app-of-apps
      targetRevision: HEAD
      ref: values
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
