apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-route
  namespace: monitoring
spec:
  routes:
    - match: Headers("Service", "prometheus")
      kind: Rule
      services:
        - name: prometheus-kube-prometheus-prometheus
          port: 9090
