apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-install
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 75.4.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/apps/prometheus/values.yaml
    - repoURL: https://github.com/adaptivekind/app-of-apps
      targetRevision: HEAD
      ref: values
  project: default
  destination:
    name: in-cluster
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
