apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  scrapeInterval: 60s
  enableAdminAPI: true
  enableRemoteWriteReceiver: true
