apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - chart: prometheus-operator
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "*"
      helm:
        releaseName: prometheus-operator
  project: project-default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
