apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-certificate
spec:
  secretName: prometheus-route-tls
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - Adaptive Kind
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.local
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-route
  namespace: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`prometheus.{domain:[a-z\.]+}`)
      kind: Rule
      services:
        - name: prometheus-operated
          port: 9090
  tls:
    secretName: prometheus-route-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-http-route
  namespace: prometheus
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`prometheus.{domain:[a-z\.]+}`)
      kind: Rule
      services:
        - name: prometheus-operated
          port: 9090
      middlewares:
        - name: redirect-to-https
