apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: scrape-kube-state-metrics
  namespace: lens
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - labels:
        job: kube-state-metrics
      targets:
        - kube-state-metrics.lens.svc.cluster.local:8080
