# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
grafana:
  enabled: false
alertmanager:
  enabled: false
service:
  enabled: false
kubeStateMetrics:
  enabled: false
kubelet:
  enabled: true
  serviceMonitor:
    probes: false
    metricRelabelings:
      # Drop metrics with a lot of series
      - action: drop
        regex: 'apiserver_(admission|cache|flowcontrol|request|response|storage|watch)_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'etcd_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'kubelet_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'prober_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'rest_client_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'scheduler_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'storage_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'workqueue_.+'
        sourceLabels: [__name__]
      - sourceLabels: [le]
        regex: '2.5'
        action: 'drop'
      - sourceLabels: [le]
        regex: '0.25'
        action: drop
      - sourceLabels: [le]
        regex: '0.025'
        action: drop
kubeApiServer:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      # Drop metrics with a lot of series
      - action: drop
        regex: 'apiserver_(admission|cache|flowcontrol|request|response|storage|watch)_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'etcd_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'kubelet_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'prober_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'rest_client_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'scheduler_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'storage_.+'
        sourceLabels: [__name__]
      - action: drop
        regex: 'workqueue_.+'
        sourceLabels: [__name__]
nodeExporter:
  enabled: true
defaultRules:
  create: false
prometheus:
  prometheusSpec:
    scrapeInterval: 60s
    enableAdminAPI: true
    remoteWrite:
      - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
        basicAuth:
          username:
            name: remote-prometheus-write-credentials
            key: username
          password:
            name: remote-prometheus-write-credentials
            key: password
        queueConfig:
          maxBackoff: "60s"
          sampleAgeLimit: "1h"
          maxSamplesPerSend: 5000
        writeRelabelConfigs:
          - sourceLabels: [__name__]
            regex: (node_cpu_*|node_memory_*|container_cpu_*|container_memory_*)
            action: keep
