# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
grafana:
  enabled: false
alertmanager:
  enabled: false
nodeExporter:
  enabled: true
defaultRules:
  create: false
prometheus:
  prometheusSpec:
    scrapeInterval: 60s
    remoteWrite:
      - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
        basicAuth:
          username:
            name: remote-prometheus-write-credentials
            key: username
          password:
            name: remote-prometheus-write-credentials
            key: password
        queueConfig:
          maxBackoff: "60s"
          sampleAgeLimit: "1h"
          maxSamplesPerSend: 5000
        writeRelabelConfigs:
          # Drop series with specific metric names
          - sourceLabels: [__name__]
            regex: "apiserver_.*"
            action: drop
          - sourceLabels: [__name__]
            regex: "etcd_.*"
            action: drop
          - sourceLabels: [__name__]
            regex: "workqueue_.*"
            action: drop
          - sourceLabels: [__name__]
            regex: "rest_client_.*"
            action: drop
