apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: examples
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    name: in-cluster
  project: default
  source:
    path: apps/examples
    repoURL: https://github.com/adaptivekind/app-of-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
