apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k3s-grafana-route
  namespace: monitoring
spec:
  routes:
    - match: Header("Service", "grafana")
      kind: Rule
      services:
        - name: grafana
          port: 80
