apiVersion: traefik.us/v1alpha1
kind: IngressRoute
metadata:
  name: lab-grafana-route
  namespace: monitoring
spec:
  routes:
    - match: Headers("Service", "grafana")
      kind: Rule
      services:
        - name: grafana-service
          port: 3000
