apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lab-grafana-route
  namespace: monitoring
  annotations:
    gethomepage.dev/href: https://grafana
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Metrics
    gethomepage.dev/group: monitoring
    gethomepage.dev/name: grafana
    gethomepage.dev/widget.type: grafana
    gethomepage.dev/widget.url: https://grafana
    gethomepage.dev/podselector: app.kubernetes.io/name=grafana
spec:
  routes:
    - match: Headers("Service", "grafana")
      kind: Rule
      services:
        - name: grafana-service
          port: 3000
