apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scaling
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: apps/scaling
    repoURL: https://github.com/adaptivekind/app-of-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
