apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd.local
spec:
  secretName: argocd.local-secret
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.local
