apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: argocd-route
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNIRegexp(`argocd.{domain:[a-z\.]+}`)
      services:
        - name: argocd-server
          port: 443
  tls:
    secretName: argocd.local-secret
