apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: argocd
  name: argocd-server-metrics
  labels:
    app: kube-prometheus-stack-operator
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
  endpoints:
  - port: metrics
