apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
spec:
  secretName: argocd-server-tls
  commonName: Argo CD
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - Adaptive Kind
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.local
