apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-local-certificate
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.local
