apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
spec:
  secretName: argocd-route-tls
  secretTemplate:
    labels:
      cluster-issuer: ca-issuer
  commonName: argocd.local
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - Adaptive Kind
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.local
