apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
   name: argocd-application-controller-scaledobject
   namespace: argocd
spec:
   scaleTargetRef:
      name: argocd-application-controller
      kind: StatefulSet
   minReplicaCount: 0
   maxReplicaCount: 1
   cooldownPeriod: 30
   triggers:
   - type: cron
     metadata:
      timezone: Europe/London
      start: 08 0 * * *         # From 8 PM
      end: 22 0 * * *           # To 10 PM
      desiredReplicas: "1"
