# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
applicationSet:
  metrics:
    enabled: true
    service:
      labels:
        "app.kubernetes.io/name": "argocd-applicationset-controller-metrics"
controller:
  metrics:
    enabled: true
dex:
  metrics:
    enabled: true
redis:
  metrics:
    enabled: true
    service:
      labels:
        "app.kubernetes.io/name": "argocd-redis-metrics"
repoServer:
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
configs:
  cm:
    timeout.reconciliation: 3600s
  params:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller
    controller.status.processors: 5
    controller.operation.processors: 3
