# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
applicationSet:
  metrics:
    enabled: false
    service:
      labels:
        "app.kubernetes.io/name": "argocd-applicationset-controller-metrics"
controller:
  metrics:
    enabled: false
dex:
  metrics:
    enabled: false
redis:
  metrics:
    enabled: false
    service:
      labels:
        "app.kubernetes.io/name": "argocd-redis-metrics"
repoServer:
  metrics:
    enabled: false
server:
  metrics:
    enabled: false
