# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
global:
  logging:
    level: info
applicationSet:
  metrics:
    enabled: false
    service:
      labels:
        "app.kubernetes.io/name": "argocd-applicationset-controller-metrics"
controller:
  # heartbeatTime: 20
  # revisionHistoryLimit: 3
  metrics:
    enabled: true
  extraArgs:
    - --app-resync 3600
    - --app-resync-jitter 300
  env:
    - name: ARGO_CD_UPDATE_CLUSTER_INFO_TIMEOUT
      value: "360"
dex:
  enabled: false
  metrics:
    enabled: false
redis:
  metrics:
    enabled: false
    service:
      labels:
        "app.kubernetes.io/name": "argocd-redis-metrics"
repoServer:
  metrics:
    enabled: true
server:
  metrics:
    enabled: false
configs:
  cm:
    timeout.reconciliation: 1d
    timeout.reconciliation.jitter: 1h
  params:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller
    controller.status.processors: 1
    controller.operation.processors: 1
    controller.repo.server.timeout.seconds: 28800
