# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
global:
  logging:
    level: warn
applicationSet:
  metrics:
    enabled: true
    service:
      labels:
        "app.kubernetes.io/name": "argocd-applicationset-controller-metrics"
controller:
  # heartbeatTime: 20
  # revisionHistoryLimit: 3
  metrics:
    enabled: true
  env:
    - ARGO_CD_UPDATE_CLUSTER_INFO_TIMEOUT=60
dex:
  metrics:
    enabled: true
redis:
  metrics:
    enabled: true
    service:
      labels:
        "app.kubernetes.io/name": "argocd-redis-metrics"
repoServer:
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
configs:
  cm:
    timeout.reconciliation: 3600s
  params:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller
    controller.status.processors: 1
    controller.operation.processors: 1
    controller.repo.server.timeout.seconds: 300
